import type { FormEvent } from 'react';
import type {
  MonorepoContextMode,
  MonorepoMode,
  MonorepoSubprojectPolicy,
  Project,
  ProjectRole,
  ResolutionKind,
} from '../lib/types';

export type Props = {
  resolutionOrder: ResolutionKind[];
  setResolutionOrder: (order: ResolutionKind[]) => void;
  autoCreateProject: boolean;
  setAutoCreateProject: (value: boolean) => void;
  autoCreateProjectSubprojects: boolean;
  setAutoCreateProjectSubprojects: (value: boolean) => void;
  autoSwitchRepo: boolean;
  setAutoSwitchRepo: (value: boolean) => void;
  autoSwitchSubproject: boolean;
  setAutoSwitchSubproject: (value: boolean) => void;
  allowManualPin: boolean;
  setAllowManualPin: (value: boolean) => void;
  enableGitEvents: boolean;
  setEnableGitEvents: (value: boolean) => void;
  enableCommitEvents: boolean;
  setEnableCommitEvents: (value: boolean) => void;
  enableMergeEvents: boolean;
  setEnableMergeEvents: (value: boolean) => void;
  enableCheckoutEvents: boolean;
  setEnableCheckoutEvents: (value: boolean) => void;
  checkoutDebounceSeconds: number;
  setCheckoutDebounceSeconds: (value: number) => void;
  checkoutDailyLimit: number;
  setCheckoutDailyLimit: (value: number) => void;
  enableActivityAutoLog: boolean;
  setEnableActivityAutoLog: (value: boolean) => void;
  enableDecisionExtraction: boolean;
  setEnableDecisionExtraction: (value: boolean) => void;
  decisionExtractionMode: 'llm_only' | 'hybrid_priority';
  setDecisionExtractionMode: (value: 'llm_only' | 'hybrid_priority') => void;
  decisionDefaultStatus: 'draft' | 'confirmed';
  setDecisionDefaultStatus: (value: 'draft' | 'confirmed') => void;
  decisionAutoConfirmEnabled: boolean;
  setDecisionAutoConfirmEnabled: (value: boolean) => void;
  decisionAutoConfirmMinConfidence: number;
  setDecisionAutoConfirmMinConfidence: (value: number) => void;
  decisionBatchSize: number;
  setDecisionBatchSize: (value: number) => void;
  decisionBackfillDays: number;
  setDecisionBackfillDays: (value: number) => void;
  activeWorkStaleDays: number;
  setActiveWorkStaleDays: (value: number) => void;
  activeWorkAutoCloseEnabled: boolean;
  setActiveWorkAutoCloseEnabled: (value: boolean) => void;
  activeWorkAutoCloseDays: number;
  setActiveWorkAutoCloseDays: (value: number) => void;
  rawAccessMinRole: ProjectRole;
  setRawAccessMinRole: (value: ProjectRole) => void;
  searchDefaultMode: 'hybrid' | 'keyword' | 'semantic';
  setSearchDefaultMode: (value: 'hybrid' | 'keyword' | 'semantic') => void;
  searchHybridAlpha: number;
  setSearchHybridAlpha: (value: number) => void;
  searchHybridBeta: number;
  setSearchHybridBeta: (value: number) => void;
  searchDefaultLimit: number;
  setSearchDefaultLimit: (value: number) => void;
  searchTypeWeightsJson: string;
  setSearchTypeWeightsJson: (value: string) => void;
  searchRecencyHalfLifeDays: number;
  setSearchRecencyHalfLifeDays: (value: number) => void;
  searchSubpathBoostWeight: number;
  setSearchSubpathBoostWeight: (value: number) => void;
  retentionPolicyEnabled: boolean;
  setRetentionPolicyEnabled: (value: boolean) => void;
  auditRetentionDays: number;
  setAuditRetentionDays: (value: number) => void;
  rawRetentionDays: number;
  setRawRetentionDays: (value: number) => void;
  retentionMode: 'archive' | 'hard_delete';
  setRetentionMode: (value: 'archive' | 'hard_delete') => void;
  githubPrefix: string;
  setGithubPrefix: (value: string) => void;
  localPrefix: string;
  setLocalPrefix: (value: string) => void;
  enableMonorepoResolution: boolean;
  setEnableMonorepoResolution: (value: boolean) => void;
  monorepoDetectionLevel: number;
  setMonorepoDetectionLevel: (value: number) => void;
  monorepoMode: MonorepoMode;
  setMonorepoMode: (value: MonorepoMode) => void;
  monorepoContextMode: MonorepoContextMode;
  setMonorepoContextMode: (value: MonorepoContextMode) => void;
  monorepoSubpathMetadataEnabled: boolean;
  setMonorepoSubpathMetadataEnabled: (value: boolean) => void;
  monorepoSubpathBoostEnabled: boolean;
  setMonorepoSubpathBoostEnabled: (value: boolean) => void;
  monorepoSubpathBoostWeight: number;
  setMonorepoSubpathBoostWeight: (value: number) => void;
  projects: Project[];
  monorepoSubprojectPolicies: MonorepoSubprojectPolicy[];
  newMonorepoPolicyRepoKey: string;
  setNewMonorepoPolicyRepoKey: (value: string) => void;
  newMonorepoPolicySubpath: string;
  setNewMonorepoPolicySubpath: (value: string) => void;
  newMonorepoPolicyEnabled: boolean;
  setNewMonorepoPolicyEnabled: (value: boolean) => void;
  monorepoPolicyReason: string;
  setMonorepoPolicyReason: (value: string) => void;
  createMonorepoSubprojectPolicy: (event?: FormEvent<Element>) => Promise<void>;
  patchMonorepoSubprojectPolicy: (id: string, enabled: boolean) => Promise<void>;
  removeMonorepoSubprojectPolicy: (id: string) => Promise<void>;
  monorepoWorkspaceGlobsText: string;
  setMonorepoWorkspaceGlobsText: (value: string) => void;
  monorepoExcludeGlobsText: string;
  setMonorepoExcludeGlobsText: (value: string) => void;
  monorepoRootMarkersText: string;
  setMonorepoRootMarkersText: (value: string) => void;
  monorepoMaxDepth: number;
  setMonorepoMaxDepth: (value: number) => void;
  workspaceSettingsReason: string;
  setWorkspaceSettingsReason: (value: string) => void;
  saveWorkspaceSettings: () => Promise<void>;
  draggingKind: ResolutionKind | null;
  setDraggingKind: (kind: ResolutionKind | null) => void;
};
